#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o noclobber
set -o nounset
#set -o xtrace

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
[ ! -z "$DIR" ]

usage() { echo "sdf2table in Docker

Use this program to generate a parse table from an SDF definition.
It can generate tables from full SDF definition files, parse trees
of full SDF definition files, or search for modules itself starting
from a top module name and using a search path.

Common usage patterns:
	$0 -c -m <topModule> -o <file>.tbl
	$0 -c -m <topModule> -p <searchPath> -o <file>.tbl
	$0 -m <topModule> -i <definitionFile>.def -o <file>.tbl
	$0 -m <topModule> -i <definitionTree>.def.pt -o <file>.tbl
	$0 -c -d -m <topModule> -o <definitionFile>.def.pt

Usage: $0 [options]
Options:
	-b              output terms in BAF format (default)
	-c              collect SDF modules from the search path
	-d              only collect an SDF definition
	-g              take kernel sdf as input and generate table
	-h              display help information (usage)
	-i filename     input from file (default stdin, can be repeated)
	-l filename     log statistic information
	-m modulename   name of top module (default Main)
	-n              only normalization of grammar
	-o filename     output to file (default stdout)
	-p path         colon separated search path for SDF modules (default '.')
	-t              output terms in plaintext format
	-v              verbose mode
	-V              reveal program version (i.e. 5.0)
" 1>&2; exit 1; }

# Read the command-line options,
# appending them to $newopts
newopts=""
declare -a vols=()
while getopts "bcdghi:l:m:no:p:tvV" o; do
    case "${o}" in
        b) newopts+=" -b" ;;
        c) newopts+=" -c" ;;
        d) newopts+=" -d" ;;
        g) newopts+=" -g" ;;
        h) newopts+=" -h" ;;
        i)
            newopts+=" -i  ${OPTARG}"
            vols+=($(realpath -s $(dirname "${OPTARG}")))
            ;;
        l)
            newopts+=" -l  ${OPTARG}"
            vols+=($(realpath -s $(dirname "${OPTARG}")))
            ;;
        m) newopts+=" -m  ${OPTARG}" ;;
        n) newopts+=" -n" ;;
        o) newopts+=" -o  ${OPTARG}"
            vols+=($(realpath -s $(dirname "${OPTARG}")))
            ;;
        #p) newopts+=" -p  ${OPTARG}" ;;    # Not supported
        t) newopts+=" -t" ;;
        v) newopts+=" -v" ;;
        V) newopts+=" -V" ;;
        *) usage ;;
    esac
done
shift $((OPTIND-1))

# Attempt to run the native sdf2table
set +o errexit
./sdf2table-native ${newopts}  # && retVal=$? || retVal=$?
retVal=$?
set -o errexit
if [[ $retVal -ne 0 && $retVal -ne 126 ]]; then
    # sdf2table ran but succeeded or failed
    exit $retVal
fi
# sdf2table didn't run, attempt run sdf2table using Docker
echo "sdf2table failed to run natively, attemping using Docker"

# Gather the volumes to mount (basically, every directory mentioned in -i, -l, or -o)
volumes=""
for i in "${vols[@]}"
do
    echo "VOLUME: $i"
    volumes+=" -v $i:$i"
done
echo $volumes

# Run the docker container with the volumes mounted, and execute sdf2table
docker run --rm -it -v "$DIR/../":/native \
  ${volumes} \
  ubuntu:focal \
  /native/linux/sdf2table ${newopts}
# `docker run` returns the exit code of its command

echo "Done"
