[
   Colorer                           -- V  [H  [KW["colorer"]] _1],
   Colorer.1:iter-star               -- _1,
   Rule                              -- _1 KW[":"] _2 _3,
   Token                             -- _1,
   TK_IDENTIFIER                     -- KW["identifier"] KW["token"],
   TK_NUMBER                         -- KW["number"] KW["token"],
   TK_STRING                         -- KW["string"] KW["token"],
   TK_KEYWORD                        -- KW["keyword"] KW["token"],
   TK_OPERATOR                       -- KW["operator"] KW["token"],
   TK_VAR                            -- KW["var"] KW["token"],
   TK_JUNK                           -- KW["junk"] KW["token"],
   TK_UNKNOWN                        -- KW["unknown"] KW["token"],
   NoFont                            -- ,
   ColorName                         -- _1,
   ColorRGB                          -- _1 _2 _3,
   RED                               -- _1,
   RED.1:ci-lit                      -- _1,
%% RED.1:ci-lit.1:"RED"              -- ,
   DARK_RED                          -- _1 _2 _3,
   DARK_RED.1:ci-lit                 -- _1,
%% DARK_RED.1:ci-lit.1:"DARK"        -- ,
   DARK_RED.2:opt                    -- _1,
   DARK_RED.2:opt.1:ci-lit           -- _1,
%% DARK_RED.2:opt.1:ci-lit.1:"_"     -- ,
   DARK_RED.3:ci-lit                 -- _1,
%% DARK_RED.3:ci-lit.1:"RED"         -- ,
   GREEN                             -- _1,
   GREEN.1:ci-lit                    -- _1,
%% GREEN.1:ci-lit.1:"GREEN"          -- ,
   DARK_GREEN                        -- _1 _2 _3,
   DARK_GREEN.1:ci-lit               -- _1,
%% DARK_GREEN.1:ci-lit.1:"DARK"      -- ,
   DARK_GREEN.2:opt                  -- _1,
   DARK_GREEN.2:opt.1:ci-lit         -- _1,
%% DARK_GREEN.2:opt.1:ci-lit.1:"_"   -- ,
   DARK_GREEN.3:ci-lit               -- _1,
%% DARK_GREEN.3:ci-lit.1:"GREEN"     -- ,
   WHITE                             -- _1,
   WHITE.1:ci-lit                    -- _1,
%% WHITE.1:ci-lit.1:"WHITE"          -- ,
   BLACK                             -- _1,
   BLACK.1:ci-lit                    -- _1,
%% BLACK.1:ci-lit.1:"BLACK"          -- ,
   YELLOW                            -- _1,
   YELLOW.1:ci-lit                   -- _1,
%% YELLOW.1:ci-lit.1:"YELLOW"        -- ,
   DARK_YELLOW                       -- _1 _2 _3,
   DARK_YELLOW.1:ci-lit              -- _1,
%% DARK_YELLOW.1:ci-lit.1:"DARK"     -- ,
   DARK_YELLOW.2:opt                 -- _1,
   DARK_YELLOW.2:opt.1:ci-lit        -- _1,
%% DARK_YELLOW.2:opt.1:ci-lit.1:"_"  -- ,
   DARK_YELLOW.3:ci-lit              -- _1,
%% DARK_YELLOW.3:ci-lit.1:"YELLOW"   -- ,
   BLUE                              -- _1,
   BLUE.1:ci-lit                     -- _1,
%% BLUE.1:ci-lit.1:"BLUE"            -- ,
   DARK_BLUE                         -- _1 _2 _3,
   DARK_BLUE.1:ci-lit                -- _1,
%% DARK_BLUE.1:ci-lit.1:"DARK"       -- ,
   DARK_BLUE.2:opt                   -- _1,
   DARK_BLUE.2:opt.1:ci-lit          -- _1,
%% DARK_BLUE.2:opt.1:ci-lit.1:"_"    -- ,
   DARK_BLUE.3:ci-lit                -- _1,
%% DARK_BLUE.3:ci-lit.1:"BLUE"       -- ,
   MAGENTA                           -- _1,
   MAGENTA.1:ci-lit                  -- _1,
%% MAGENTA.1:ci-lit.1:"MAGENTA"      -- ,
   DARK_MAGENTA                      -- _1 _2 _3,
   DARK_MAGENTA.1:ci-lit             -- _1,
%% DARK_MAGENTA.1:ci-lit.1:"DARK"    -- ,
   DARK_MAGENTA.2:opt                -- _1,
   DARK_MAGENTA.2:opt.1:ci-lit       -- _1,
%% DARK_MAGENTA.2:opt.1:ci-lit.1:"_" -- ,
   DARK_MAGENTA.3:ci-lit             -- _1,
%% DARK_MAGENTA.3:ci-lit.1:"MAGENTA" -- ,
   GRAY                              -- _1,
   GRAY.1:ci-lit                     -- _1,
%% GRAY.1:ci-lit.1:"GRAY"            -- ,
   DARK_GRAY                         -- _1 _2 _3,
   DARK_GRAY.1:ci-lit                -- _1,
%% DARK_GRAY.1:ci-lit.1:"DARK"       -- ,
   DARK_GRAY.2:opt                   -- _1,
   DARK_GRAY.2:opt.1:ci-lit          -- _1,
%% DARK_GRAY.2:opt.1:ci-lit.1:"_"    -- ,
   DARK_GRAY.3:ci-lit                -- _1,
%% DARK_GRAY.3:ci-lit.1:"GRAY"       -- ,
   Outliner                          -- V  [H  [KW["outliner"]] _1],
   Outliner.1:iter-star              -- _1,
   Folding                           -- V  [H  [KW["folding"]] _1],
   Folding.1:iter-star               -- _1,
   Sort                              -- _1,
   ListSort                          -- _1 KW["*"],
   Constructor                       -- KW["."] _1,
   SortAndConstructor                -- _1 KW["."] _2,
   Module                            -- KW["module"] _1 _2 _3,
   Module.3:iter-star                -- _1,
   Imports                           -- V  [H  [KW["imports"]] _1],
   Imports.1:iter-sep                -- _1 KW[","],
   Imports                           -- _1,
   Imports.1:iter-star               -- _1
]
