[
   Colorer              -- V  [H  [KW["colorer"]] _1],
   Colorer.1:iter-star  -- _1,
   Rule                 -- _1 KW[":"] _2 _3 _4,
   Rule.3:opt           -- _1,
   Token                -- _1,
   TK_IDENTIFIER        -- KW["identifier"] KW["token"],
   TK_NUMBER            -- KW["number"] KW["token"],
   TK_STRING            -- KW["string"] KW["token"],
   TK_KEYWORD           -- KW["keyword"] KW["token"],
   TK_OPERATOR          -- KW["operator"] KW["token"],
   TK_VAR               -- KW["var"] KW["token"],
   TK_JUNK              -- KW["junk"] KW["token"],
   TK_UNKNOWN           -- KW["unknown"] KW["token"],
   NORMAL               -- ,
   BOLD                 -- KW["bold"],
   ITALIC               -- KW["italic"],
   ColorName            -- _1,
   ColorRGB             -- _1 _2 _3,
   RED                  -- KW["red"],
   DARK_RED             -- KW["dark"] KW["red"],
   GREEN                -- KW["green"],
   DARK_GREEN           -- KW["dark"] KW["green"],
   WHITE                -- KW["white"],
   BLACK                -- KW["black"],
   YELLOW               -- KW["yellow"],
   DARK_YELLOW          -- KW["dark"] KW["yellow"],
   BLUE                 -- KW["blue"],
   DARK_BLUE            -- KW["dark"] KW["blue"],
   MAGENTA              -- KW["magenta"],
   DARK_MAGENTA         -- KW["dark"] KW["magenta"],
   GRAY                 -- KW["gray"],
   DARK_GRAY            -- KW["dark"] KW["gray"],
   Outliner             -- V  [H  [KW["outliner"]] _1],
   Outliner.1:iter-star -- _1,
   Folding              -- V  [H  [KW["folding"]] _1],
   Folding.1:iter-star  -- _1,
   Sort                 -- _1,
   ListSort             -- _1 KW["*"],
   Constructor          -- KW["."] _1,
   SortAndConstructor   -- _1 KW["."] _2,
   Module               -- KW["module"] _1 _2 _3,
   Module.3:iter-star   -- _1,
   Imports              -- V  [H  [KW["imports"]] _1],
   Imports.1:iter-sep   -- _1 KW[","],
   Imports              -- _1,
   Imports.1:iter-star  -- _1
]
